### ISSUE TITLE
Export existing help into markdown format.

### ISSUE THREAD

**Issue by kasperosterbye** [pharo-spec/NewTools-DocumentationReader#6]
I have made an exporter which can convert the existing help into microdown format.
As this is a one time thing, it is not clear this code should be permanently in the image. The tool is therefore included here as a file-in, which overwrites some parts of the existing help system. 

[HelpSystem-Core.st.zip](https://github.com/pharo-spec/NewTools-DocumentationReader/files/7208482/HelpSystem-Core.st.zip)

**Comment by Ducasse** [comment]
Cool good idea. Why not publishing the package without adding it to the baseline?
LIke that we can version it and have access to it from github and we can still remove it after.

**Comment by kasperosterbye** [comment]
This is now a PR in Pharo. It required some refactoring of the HelpSystem. I close it here.
