### ISSUE TITLE
Refactor StHelpBrowserPresenter 

### ISSUE THREAD

**Issue by kasperosterbye** [pharo-spec/NewTools-DocumentationReader#8]
I believe `StHelpBrowserPresenter` actually does two things:
- composes directories and md-files into a topic structure
- presents a topic structure where the leafs are microdown

I believe it would be beneficial to split this into two classes according to those two roles.

In addition, StHelpBrowserPresenter caches previous files using the memory file system. I believe the caching is necessary - in particular for the `StGithubDocFolderBuilder` (PR #7)  which is rather slow. 

Rather than caching files, `StHelpBrowserPresenter` could cache the topic tree, independent of how it was obtained.

**Comment by Ducasse** [comment]
Indeed caching the tree looks a good idea.
Good idea to split we should be able to test independently.

**Comment by kasperosterbye** [comment]
PR #7 fixes this.
